sonar.projectKey=daddandrea_pong_game
sonar.organization=daddandrea-organization
sonar.sources=src
sonar.exclusions=third_party/**
sonar.cfamily.compile-commands=build-wrapper-output/compile_commands.json
sonar.projectName=pong_game
#sonar.projectVersion=
