sonar.projectKey=daddandrea_pong_game
sonar.organization=daddandrea-organization
sonar.sources=src
sonar.exclusions=third_party/**
sonar.cfamily.build-wrapper-output=build-wrapper-output
sonar.projectName=pong_game
#sonar.projectVersion=
